### ISSUE TITLE
Strict requirements are no fun

### ISSUE THREAD

**Issue by crempp** [launchdarkly/python-client#35]
Would it be possible to update the requirements.txt to not use strict (==) requirements? This has forced me to downgrade requests to 2.4.0.

**Comment by jkodumal** [comment]
Certainly-- we can make that change.

**Comment by witten** [comment]
Additionally, it's generally considered bad practice (especially for a library) to slurp in requirements.txt and use it for a setup.py's install_requires. Check out this article on the subject: https://caremad.io/2013/07/setup-vs-requirement/

**Comment by pkaeding** [comment]
From my understanding, it looks like the objections raised in that article are around making sure that you do not have strict requirements in the setup.py, right?

So unless I'm misinterpreting something, it should be safe to relax the requirements in requirements.txt, and still reference that from setup.py.

**Comment by witten** [comment]
That's certainly part of it, but the other part is that libraries specifically shouldn't include a requirements.txt at all, because they shouldn't have any strict/concrete requirements (and concrete requirements is the purpose of a requirements file). So it really would be more in the spirit of that article not to have a requirements.txt for your library, and put all abstract/non-strict requirements directly in your setup.py instead.
