### ISSUE TITLE
"Missing or blank sdk key" log warning message upon importing ldclient

### ISSUE THREAD

**Issue by pdsarin** [launchdarkly/python-client#65]
A warning is logged upon import of ldclient. IMO should either be logged at a lower level, or not at all as there's nothing I can do to prevent it.

`WARNING  2016-12-13 23:53:09,950 config.py:43 - ldclient.util - __init__: Missing or blank sdk_key.`

**Comment by c4pone** [comment]
Got the same issue. It's because the Config object gets created in the init file without any arguments. Then inside the Config class is a check if the sdk_key is empty.

See here:
https://github.com/launchdarkly/python-client/blob/master/ldclient/__init__.py#L19
https://github.com/launchdarkly/python-client/blob/master/ldclient/config.py#L42
